name: Frigate Rockchip
version: 0.15.1-rk
panel_icon: "mdi:cctv"
panel_title: Frigate
slug: frigate-rockchip
description: NVR with realtime local object detection for IP cameras
url: "https://github.com/blakeblackshear/frigate"
image: ghcr.io/blakeblackshear/frigate
startup: application
boot: auto
init: false
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
homeassistant_api: true
hassio_api: true
ports:
  8555/tcp: 8555
  8555/udp: 8555
  8554/tcp: false
  8971/tcp: false
  5000/tcp: false
  1984/tcp: false
  1935/tcp: false
ports_description:
  8555/tcp: WebRTC over tcp
  8555/udp: WebRTC over udp
  8554/tcp: RTSP Restream
  8971/tcp: Authenticated Web interface
  5000/tcp: Unauthenticated Web interface (Not required for Hass.io Ingress)
  1984/tcp: go2rtc API
host_network: false
usb: true
video: true
tmpfs: true
full_access: false
privileged:
  - PERFMON
  - SYS_ADMIN
environment:
  CONFIG_FILE: /config/frigate.yml
schema:
  plus_api_key: password?
services:
  - "mqtt:want"
arch:
  - aarch64
map:
  - "media:rw"
  - "config:rw"
  - "ssl:ro"
