name: "XiaoMusic"
version: "v0.3.77"
slug: "xiaomusic"
panel_icon: "mdi:music-box"
description: "Xiaomusic for Home Assistant Addons"
url: https://github.com/hanxi/xiaomusic
image: hanxi/xiaomusic:"{{ version }}"
init: false
arch:
  - amd64
  - aarch64
startup: "services"
boot: "auto"
apparmor: false
webui: "http://[HOST]:[PORT:8090]/"
ports:
  8090/tcp: 8090
options:
  music_dir: "/media/music"
  port_mapping: "8090"
schema:
  music_dir: "str?"
  port_mapping: "str?"
map:
  - "/media/music:/app/music:rw"
  - "/conf:/app/conf:rw"
